server:
 port: 8080
 servlet:
    context-path: "/accountsservice"
spring:
  application:
    name: "accountsservice"
  config:
    import: "optional:configserver:http://localhost:8081/"
  profiles:
    active:
    - "qa"
  devtools:
    add-properties: true
  cache:
    type: "none"

  rabbitmq:
     host: "localhost"
     port: 5672
     username: "guest"
     password: "guest"

management:
    endpoints:
      web:
       exposure:
         include: "*"